version: '3.8'
services:
  api:
    build: ./docker/api/
    restart: on-failure
    ports:
      - 3001:3001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:3001/healthz || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postAdmUsr2023
      POSTGRES_PASSWORD: p@ssWordPostG2ade
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postAdmUsr2023" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db:
    driver: local
