version: '3.8'
services:
  api:
    build: /docker/api/.
    restart: on-failure
    ports:
      - 3001:3001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:3001/healthz || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://localhost:5432
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start

  db:
    build:
      context: /docker/db/.
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cgp_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "username" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
